### ISSUE TITLE
requests not installed and ModuleNotFoundError error with python 3

### ISSUE THREAD

**Issue by davecoutts** [vincentlaucsb/sqlify#3]
```bash
(sqlify3) dave@asr:/tmp$ python -V
Python 3.5.2
(sqlify3) dave@asr:/tmp$ pip list
Package    Version
---------- -------
pip        9.0.1  
psycopg2   2.7.1  
setuptools 36.2.0 
sqlify     1.0.0b2
wheel      0.29.0 
(sqlify3) dave@asr:/tmp$ python
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlify
/home/dave/.virtualenvs/sqlify3/lib/python3.5/site-packages/sqlify/config.py:108: UserWarning: No default Postgres settings found. Use sqlify.settings(username='', password='', database='', hostname='') to set them.
  warnings.warn("No default Postgres settings found. Use sqlify.settings(username='', password='', database='', hostname='') to set them.")
Traceback (most recent call last):
  File "/home/dave/.virtualenvs/sqlify3/lib/python3.5/site-packages/sqlify/html/parser.py", line 2, in <module>
    import requests
ImportError: No module named 'requests'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dave/.virtualenvs/sqlify3/lib/python3.5/site-packages/sqlify/__init__.py", line 55, in <module>
    from .html import from_file, from_url
  File "/home/dave/.virtualenvs/sqlify3/lib/python3.5/site-packages/sqlify/html/__init__.py", line 1, in <module>
    from .parser import get_tables_from_file as from_file, \
  File "/home/dave/.virtualenvs/sqlify3/lib/python3.5/site-packages/sqlify/html/parser.py", line 4, in <module>
    except ModuleNotFoundError:
NameError: name 'ModuleNotFoundError' is not defined
>>> quit()
```

**Comment by vincentlaucsb** [comment]
Hi Dave,

Thanks for the detailed report.

In order to allow optional dependencies, like requests, I tried to catch the exception that occurred when you tried to import it. The problem was that Python 3.6 uses ModuleNotFoundError whereas earlier versions use ImportError. Because ModuleNotFoundError is a subclass of ImportError, just catching that works for all versions. I've updated my package to implement that fix.

I've ran my test suite on Python 3.3 and 3.5 and they've passed with flying colors, so I'm going to close this now. A new release is now available at https://pypi.org/project/sqlify/.

Cheers.
